//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogTemp.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Author_ID { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Post_Content { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> ViewCount { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
